language: php

php:
  - 5.3

mysql:
  database: drupal
  username: root
  encoding: utf8
  
before_script:
  - "mysql -e 'create database drupal;'"
  - pear channel-discover pear.drush.org
  - pear install drush/drush
  - pear install PHP_CodeSniffer
  - wget http://ftp.drupal.org/files/projects/drupalcs-7.x-1.0-beta1.tar.gz -O ../drupalcs.tar.gz
  - tar -xvzf ../drupalcs.tar.gz -C ../
  - pwd
  - phpenv rehash
  - drush make fjvu_dk.build ../fjvu.dk
  - cd ../fjvu.dk
  - sudo chmod -R 777 sites/all/modules
  - drush si fjvu_dk --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=VIH@2012 --site-mail=admin@example.com --site-name="fjvu.dk" --yes
  - drush cc all --yes
  - cd ../fjvu-deploy

script: 
  - test -d ../fjvu.dk/profiles/fjvu_dk
  - test -d ../fjvu.dk/profiles/fjvu_dk/modules/contrib
  - test -d ../fjvu.dk/profiles/fjvu_dk/modules/fjvu
  - test -d ../fjvu.dk/profiles/fjvu_dk/themes
  - phpcs . --standard=../drupalcs/Drupal/ruleset.xml --extensions=php,module,inc,install,test,profile,theme
