api = 2
core = 6.x

;contrib
projects[admin][subdir] = "contrib"
projects[advanced_help][subdir] = "contrib"
projects[backup_migrate][subdir] = "contrib"
projects[calendar][subdir] = "contrib"
projects[cck][subdir] = "contrib"
projects[comment_notify][subdir] = "contrib"
projects[content_taxonomy][subdir] = "contrib"
projects[ctools][subdir] = "contrib"
projects[date][subdir] = "contrib"
projects[emfield][subdir] = "contrib"
projects[fckeditor][subdir] = "contrib"
projects[features][subdir] = "contrib"
projects[filefield][subdir] = "contrib"
projects[flag][subdir] = "contrib"
projects[globalredirect][subdir] = "contrib"
projects[google_analytics][subdir] = "contrib"
projects[i18n][subdir] = "contrib"
projects[imageapi][subdir] = "contrib"
projects[imagecache][subdir] = "contrib"
projects[imagefield][subdir] = "contrib"
projects[imce][subdir] = "contrib"
projects[isbn][subdir] = "contrib"
projects[jquery_ui][subdir] = "contrib"
projects[nodewords][subdir] = "contrib"
projects[nodewords_nodetype][subdir] = "contrib"
projects[pathauto][subdir] = "contrib"
projects[path_redirect][subdir] = "contrib"
projects[scheduler][subdir] = "contrib"
projects[scribdfield][subdir] = "contrib"
projects[scribdfield][version] = "1.x-dev"
projects[signup][subdir] = "contrib"
projects[similarterms][subdir] = "contrib"
projects[subscriptions][subdir] = "contrib"
projects[strongarm][subdir] = "contrib"
projects[token][subdir] = "contrib"
projects[transliteration][subdir] = "contrib"
projects[views][subdir] = "contrib"
projects[webfm][subdir] = "contrib"
projects[xmlsitemap][subdir] = "contrib"

;themes
projects[tao][subdir] = "contrib"
projects[tao][type] = "theme"
projects[rubik][subdir] = "contrib"
projects[rubik][type] = "theme"

projects[fjernvarme][type] = "theme"
projects[fjernvarme][download][type] = "git"
projects[fjernvarme][download][url] = "git://github.com/fjvu/fjernvarme-theme.git"

;libraries
libraries[fckeditor][download][type] = "get"
libraries[fckeditor][download][url] = "http://sourceforge.net/projects/fckeditor/files/FCKeditor/2.6.6/FCKeditor_2.6.6.tar.gz/download"
libraries[fckeditor][directory_name] = "fckeditor"
libraries[fckeditor][destination] = "libraries"

libraries[jquery_ui][download][type] = "get"
libraries[jquery_ui][download][url] = "http://jquery-ui.googlecode.com/files/jquery.ui-1.6.zip"
libraries[jquery_ui][directory_name] = "jquery.ui"
libraries[jquery_ui][destination] = "modules/contrib/jquery_ui"
