api = 2
core = 6.x

;contrib
projects[admin_menu][subdir] = "contrib"
projects[advanced_help][subdir] = "contrib"
projects[backup_migrate][subdir] = "contrib"
projects[calendar][subdir] = "contrib"
projects[cck][subdir] = "contrib"
projects[comment_notify][subdir] = "contrib"
projects[ctools][subdir] = "contrib"
projects[date][subdir] = "contrib"
projects[emfield][subdir] = "contrib"
projects[fckeditor][subdir] = "contrib"
projects[filefield][subdir] = "contrib"
projects[fivestar][subdir] = "contrib"
projects[flag][subdir] = "contrib"
projects[globalredirect][subdir] = "contrib"
projects[google_analytics][subdir] = "contrib"
projects[i18n][subdir] = "contrib"
projects[imageapi][subdir] = "contrib"
projects[imagecache][subdir] = "contrib"
projects[imagefield][subdir] = "contrib"
projects[imce][subdir] = "contrib"
projects[mass_contact][subdir] = "contrib"
projects[mimedetect][subdir] = "contrib"
projects[nodewords][subdir] = "contrib"
projects[nodewords_nodetype][subdir] = "contrib"
projects[pathauto][subdir] = "contrib"
projects[path_redirect][subdir] = "contrib"
projects[scheduler][subdir] = "contrib"
projects[similarterms][subdir] = "contrib"
projects[signup][subdir] = "contrib"
projects[similarterms][subdir] = "contrib"
projects[subscriptions][subdir] = "contrib"
projects[token][subdir] = "contrib"
projects[transliteration][subdir] = "contrib"
projects[views][subdir] = "contrib"
projects[votingapi][subdir] = "contrib"
projects[webfm][subdir] = "contrib"
projects[xmlsitemap][subdir] = "contrib"

;libraries
libraries[fckeditor][download][type] = "get"
libraries[fckeditor][download][url] = "http://sourceforge.net/projects/fckeditor/ffiles/FCKeditor/2.6.4/FCKeditor_2.6.4.zip/download"
libraries[fckeditor][directory_name] = "fckeditor"
libraries[fckeditor][destination] = "libraries
