api = 2
core = 6.x

;contrib
<<<<<<< HEAD
projects[acl][subdir] = "contrib"
projects[addthis][subdir] = "contrib"
=======
>>>>>>> 336e6dcc6f2f45a78d9f43d428522c8ae69e77a9
projects[admin_menu][subdir] = "contrib"
projects[advanced_help][subdir] = "contrib"
projects[backup_migrate][subdir] = "contrib"
projects[calendar][subdir] = "contrib"
projects[cck][subdir] = "contrib"
projects[comment_notify][subdir] = "contrib"
<<<<<<< HEAD
projects[ctools][subdir] = "contrib"
projects[date][subdir] = "contrib"
projects[diggthis][subdir] = "contrib"
projects[emfield][subdir] = "contrib"
projects[fbconnect][subdir] = "contrib"
projects[fckeditor][subdir] = "contrib"
projects[filefield][subdir] = "contrib"
projects[fivestar][subdir] = "contrib"
projects[flag][subdir] = "contrib"
projects[forum_access][subdir] = "contrib"
=======
projects[content_taxonomy][subdir] = "contrib"
projects[ctools][subdir] = "contrib"
projects[date][subdir] = "contrib"
projects[emfield][subdir] = "contrib"
projects[fckeditor][subdir] = "contrib"
projects[features][subdir] = "contrib"
projects[filefield][subdir] = "contrib"
projects[fivestar][subdir] = "contrib"
projects[flag][subdir] = "contrib"
>>>>>>> 336e6dcc6f2f45a78d9f43d428522c8ae69e77a9
projects[globalredirect][subdir] = "contrib"
projects[google_analytics][subdir] = "contrib"
projects[i18n][subdir] = "contrib"
projects[imageapi][subdir] = "contrib"
projects[imagecache][subdir] = "contrib"
projects[imagefield][subdir] = "contrib"
projects[imce][subdir] = "contrib"
<<<<<<< HEAD
projects[masscontact][subdir] = "contrib"
projects[mimedetect][subdir] = "contrib"
projects[node_import][subdir] = "contrib"
projects[nodewords][subdir] = "contrib"
projects[nodewords_nodetype][subdir] = "contrib"
projects[panels][subdir] = "contrib"
projects[pathauto][subdir] = "contrib"
projects[path_redirect][subdir] = "contrib"
projects[scheduler][subdir] = "contrib"
projects[similarterms][subdir] = "contrib"
projects[schema][subdir] = "contrib"
projects[search404][subdir] = "contrib"
projects[signup][subdir] = "contrib"
projects[similarterms][subdir] = "contrib"
projects[subscriptions][subdir] = "contrib"
projects[tagadelic][subdir] = "contrib"
projects[token][subdir] = "contrib"
projects[tw][subdir] = "contrib"
projects[transliteration][subdir] = "contrib"
projects[user_import][subdir] = "contrib"
projects[views][subdir] = "contrib"
projects[views_bulk_operations][subdir] = "contrib"
projects[voting_api][subdir] = "contrib"
projects[webform][subdir] = "contrib"
projects[webform_report][subdir] = "contrib"
projects[webfm][subdir] = "contrib"
projects[wysiwyg][subdir] = "contrib"
projects[xmlsitemap][subdir] = "contrib"
=======
projects[jquery_ui][subdir] = "contrib"
projects[nodewords][subdir] = "contrib"
projects[nodewords_nodetype][subdir] = "contrib"
projects[pathauto][subdir] = "contrib"
projects[path_redirect][subdir] = "contrib"
projects[scheduler][subdir] = "contrib"
projects[scribdfield][subdir] = "contrib"
projects[scribdfield][version] = "1.x-dev"
projects[signup][subdir] = "contrib"
projects[similarterms][subdir] = "contrib"
projects[subscriptions][subdir] = "contrib"
projects[strongarm][subdir] = "contrib"
projects[token][subdir] = "contrib"
projects[transliteration][subdir] = "contrib"
projects[views][subdir] = "contrib"
projects[votingapi][subdir] = "contrib"
projects[webfm][subdir] = "contrib"
projects[xmlsitemap][subdir] = "contrib"

;themes
projects[fjernvarme][type] = "theme"
projects[fjernvarme][download][type] = "git"
projects[fjernvarme][download][url] = "git://github.com/fjvu/fjernvarme-theme.git"

;libraries
libraries[fckeditor][download][type] = "get"
libraries[fckeditor][download][url] = "http://sourceforge.net/projects/fckeditor/files/FCKeditor/2.6.6/FCKeditor_2.6.6.tar.gz/download"
libraries[fckeditor][directory_name] = "fckeditor"
libraries[fckeditor][destination] = "libraries"

libraries[jquery_ui][download][type] = "get"
libraries[jquery_ui][download][url] = "http://jquery-ui.googlecode.com/files/jquery.ui-1.6.zip"
libraries[jquery_ui][directory_name] = "jquery.ui"
libraries[jquery_ui][destination] = "modules/contrib/jquery_ui"
>>>>>>> 336e6dcc6f2f45a78d9f43d428522c8ae69e77a9
